name: goc-seed
description: "Parse + route + dry-run search (no creates/writes)"
inputs:
  seeds_glob:
    required: false
    description: "Glob 'dir/*.md' or single file"
  project_url_override:
    required: false
  link_after_seed:
    required: false
  dry_run:
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        node --version
        echo "::notice::[goc-seed] parse+search (dry-run)"
        node scripts/goc/runner.goc-seed.js
      env:
        INPUT_SEEDS_GLOB: ${{ inputs.seeds_glob }}
        INPUT_PROJECT_URL_OVERRIDE: ${{ inputs.project_url_override }}
        INPUT_LINK_AFTER_SEED: ${{ inputs.link_after_seed }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        PROJECT_URL: ${{ env.PROJECT_URL }}
        PROJECT_URL_TEST: ${{ env.PROJECT_URL_TEST }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
