name: goc-seed (stub)
description: Parse seed, create issue, add to Project, write fields (E1 stub: logs inputs only)
inputs:
  seeds_glob: { required: false, description: Glob of seed files }
  project_url_override: { required: false }
  link_after_seed: { required: false }
outputs:
  created:
    description: Count created (stubbed)
    value: "0"
  skipped:
    description: Count skipped (stubbed)
    value: "0"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice title=goc-seed(stub)::seeds_glob='${{ inputs.seeds_glob }}' project_url_override='${{ inputs.project_url_override }}' link_after_seed='${{ inputs.link_after_seed }}'"
