name: goc-seed
description: Parse seed, create issue, add to Project, write fields (E2.2 wiring; behavior neutral until workflows use it)
inputs:
  seeds_glob: { required: false, description: Glob or file path for seed(s) }
  project_url_override: { required: false }
  link_after_seed: { required: false }
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice::[goc-seed] setup Node toolchain"
        npm ci --ignore-scripts
        npm run build:goc
    - shell: bash
      env:
        INPUT_SEEDS_GLOB: ${{ inputs.seeds_glob }}
        INPUT_PROJECT_URL_OVERRIDE: ${{ inputs.project_url_override }}
        INPUT_LINK_AFTER_SEED: ${{ inputs.link_after_seed }}
        PROJECT_URL: ${{ vars.PROJECT_URL }}
        PROJECT_URL_TEST: ${{ vars.PROJECT_URL_TEST }}
      run: |
        node dist/goc/runners.goc-seed.js
