name: goc-seed
description: "Parse-only: logs seed headers and routing (no API calls)"
inputs:
  seeds_glob:
    required: false
    description: "Glob 'dir/*.md' or single file"
  project_url_override:
    required: false
  link_after_seed:
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        node --version
        echo "::notice::[goc-seed] parse-only run"
        node scripts/goc/runner.goc-seed.js
      env:
        INPUT_SEEDS_GLOB: ${{ inputs.seeds_glob }}
        INPUT_PROJECT_URL_OVERRIDE: ${{ inputs.project_url_override }}
        INPUT_LINK_AFTER_SEED: ${{ inputs.link_after_seed }}
        PROJECT_URL: ${{ env.PROJECT_URL }}
        PROJECT_URL_TEST: ${{ env.PROJECT_URL_TEST }}
