name: goc-seed
description: "Stub: logs inputs/env only (safe mode)"
inputs:
  seeds_glob:
    required: false
  project_url_override:
    required: false
  link_after_seed:
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice title=goc-seed(stub)::seeds_glob='${{ inputs.seeds_glob }}' project_url_override='${{ inputs.project_url_override }}' link_after_seed='${{ inputs.link_after_seed }}'"
        echo "::notice::PROJECT_URL(from env)='${{ env.PROJECT_URL }}'"
        echo "::notice::PROJECT_URL_TEST(from env)='${{ env.PROJECT_URL_TEST }}'"
