name: goc-project-set-fields
description: Write Project fields for an issue (E2.2 wiring)
inputs:
  project_url: { required: false }
  issue_node_id: { required: false }
  type: { required: false }
  status: { required: false }
  priority: { required: false }
  target: { required: false }
  area: { required: false }
  doc: { required: false }
  pr: { required: false }
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice::[goc-project-set-fields] setup Node toolchain"
        npm ci --ignore-scripts
        npm run build:goc
    - shell: bash
      env:
        INPUT_PROJECT_URL: ${{ inputs.project_url }}
        INPUT_ISSUE_NODE_ID: ${{ inputs.issue_node_id }}
        INPUT_TYPE: ${{ inputs.type }}
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_PRIORITY: ${{ inputs.priority }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT_AREA: ${{ inputs.area }}
        INPUT_DOC: ${{ inputs.doc }}
        INPUT_PR: ${{ inputs.pr }}
      run: |
        node dist/goc/runners.goc-project-set-fields.js
