name: gh-link-hierarchy
description: Create native Sub-issues links (E2.2 wiring)
inputs:
  parent_number: { required: false }
  parent_uid: { required: false }
  child_number: { required: false }
  child_uid: { required: false }
  library_path: { required: false }
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice::[gh-link-hierarchy] setup Node toolchain"
        npm ci --ignore-scripts
        npm run build:goc
    - shell: bash
      env:
        INPUT_PARENT_NUMBER: ${{ inputs.parent_number }}
        INPUT_PARENT_UID: ${{ inputs.parent_uid }}
        INPUT_CHILD_NUMBER: ${{ inputs.child_number }}
        INPUT_CHILD_UID: ${{ inputs.child_uid }}
        INPUT_LIBRARY_PATH: ${{ inputs.library_path }}
      run: |
        node dist/goc/runners.gh-link-hierarchy.js
