name: gh-link-hierarchy
description: Stub: logs inputs only (safe mode)
inputs:
  parent_number: { required: false }
  parent_uid: { required: false }
  child_number: { required: false }
  child_uid: { required: false }
  library_path: { required: false }
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice title=gh-link-hierarchy(stub)::parent#='${{ inputs.parent_number }}' parent_uid='${{ inputs.parent_uid }}' child#='${{ inputs.child_number }}' child_uid='${{ inputs.child_uid }}' lib='${{ inputs.library_path }}'"
