name: gh-link-hierarchy (stub)
description: Create native Sub-issues links (E1 stub: logs inputs only)
inputs:
  parent_number: { required: false }
  parent_uid: { required: false }
  child_number: { required: false }
  child_uid: { required: false }
  library_path: { required: false }
outputs:
  linked:
    description: Whether a link was created (stubbed)
    value: "false"
  skipped_reason:
    description: Reason for skip
    value: "stub"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "::notice title=gh-link-hierarchy(stub)::parent=#${{ inputs.parent_number }} parent_uid=${{ inputs.parent_uid }} child=#${{ inputs.child_number }} child_uid=${{ inputs.child_uid }} lib=${{ inputs.library_path }}"
