# .github/workflows/goc-seed-prod.yml
name: GOC Seed (prod)

on:
  push:
    paths:
      - ".github/project-seeds/pending/**.md"
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply changes? (true/false). For manual runs only."
        required: false
        default: "false"
        type: string
      dry_run:
        description: "Dry run? (true/false). For manual runs only."
        required: false
        default: "true"
        type: string

concurrency:
  group: goc-seed-prod
  cancel-in-progress: false

jobs:
  seed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    # Resolve flags differently for push vs manual:
    # - For push: use repo vars (set in Settings → Actions → Variables)
    #   - GOC_SEED_APPLY_PUSH: "true" to actually create; default "false"
    #   - GOC_SEED_DRY_RUN_PUSH: "true" or "false" (default "true")
    # - For workflow_dispatch: use the UI inputs
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECTS_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
      PROJECT_URL: ${{ vars.PROJECT_URL }}
      PROJECT_URL_TEST: ${{ vars.PROJECT_URL_TEST }}
      # Decide flags per event
      INPUT_APPLY: ${{ github.event_name == 'push'
        && (vars.GOC_SEED_APPLY_PUSH != '' && vars.GOC_SEED_APPLY_PUSH || 'false')
        || (inputs.apply != '' && inputs.apply || 'false') }}
      INPUT_DRY_RUN: ${{ github.event_name == 'push'
        && (vars.GOC_SEED_DRY_RUN_PUSH != '' && vars.GOC_SEED_DRY_RUN_PUSH || 'true')
        || (inputs.dry_run != '' && inputs.dry_run || 'true') }}

    steps:
      - uses: actions/checkout@v4

      - name: Seed project items (prod)
        uses: ./.github/actions/goc-seed
        with:
          seeds_glob: ".github/project-seeds/pending/**.md"
          apply: ${{ env.INPUT_APPLY }}
          dry_run: ${{ env.INPUT_DRY_RUN }}
