name: GOC Smoke (manual)

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run goc-seed (smoke)
        uses: ./.github/actions/goc-seed
        with:
          seeds_glob: ".github/project-seeds/_smoke/*.md"
          apply: "true"
          dry_run: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECTS_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
          PROJECT_URL: ${{ vars.PROJECT_URL }}
          PROJECT_URL_TEST: ${{ vars.PROJECT_URL_TEST }}
