# Supabase credentials
SUPABASE_URL = "https://byztmlhsprlovkvizyks.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5enRtbGhzcHJsb3Zrdml6eWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODI5MzgsImV4cCI6MjA2Mzg1ODkzOH0.D1z7v7rNHLLGxJHvYcIJDBN6QyuWtuPzV4-ZqM_f7mk"
CHEF_PASSWORD = "f!ref0rge"